kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gamestore-admin
  namespace: gamestore
subjects:
- kind: ServiceAccount
  name: ns-reconciler-gamestore
  namespace: config-management-system
- kind: User
  name: admin@gamestore.com
  namespace: rbac.authorization.k8s.io
- kind: AnotherUser
  name: AnotherAdmin@gamestore.com
  namespace: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
